#! /bin/bash
TCCOMMAND="$1"
shift
tc_hostnamectl(){
 [ "$1" ] || { echo "   Static hostname: $(cat $TCROOT/etc/hostname)"; return; }
 case $1 in
   set-hostname)
     echo $2 > $TCROOT/etc/hostname
     ;;
   *)
     echo "$1 NOT IMPLEMENTED"
     return 1
 esac
}

case $TCCOMMAND in
  hostnamectl)
    tc_hostnamectl "$@"
    ;;
  *)
    exit 1
esac
