#! /bin/bash
TCCOMMAND=$1
. $TCROOT/etc/os-release
bool(){
  case $1 in
                0|f|F|false|n|N|no) return 1 ;;
                1|t|T|true|y|Y|yes) return 0 ;;
                *) return 1 ;;
        esac
}
tc_hostnamectl(){
	if [ "x$1" = "x" ]
	then
	echo "   Static hostname: `cat $TCROOT/etc/hostname`"
	echo "        Machine ID: `cat $TCROOT/etc/machine-id`"
	echo "  Operating System: $PRETTY_NAME"
	return
	else
		case $1 in
			set-hostname)
				echo $2 > $TCROOT/etc/hostname
				;;
			*)
				echo "Unknown operation $1"
				return 1
				;;
		esac
	fi
}
tc_localectl(){
	if [ "x$1" = "x" ]
	then
	echo "   System Locale: `cat $TCROOT/etc/locale.conf`"
	[ -f $TCROOT/etc/vconsole.conf ] && echo "       VC Keymap: `cat $TCROOT/etc/vconsole.conf | grep ^KEYMAP\\= | cut -d = -f 2-`" || 
		echo "       VC Keymap: n/a"
	return
	else
		case $1 in 
			set-locale)
				echo $2 > $TCROOT/etc/locale.conf
				;;
			*)
				echo "Unknown operation $1"
				return 1
				;;
		esac
	fi
}
tc_timedatectl(){
	if [ "x$1" = "x" ]
	then
		# TODO: a ugly hack
		TTZ=`readlink $TCROOT/etc/localtime  | cut -d o -f 3- | cut -c 2-`
		echo "      Local time: `TZ=$TTZ date --iso-8601=seconds`"
		echo "  Universal time: `TZ=UTC date --iso-8601=seconds`"
		echo "        RTC time: `hwclock -r`"
		echo "       Time zone: $TTZ "
		grep '[Ll][Oo][Cc][Aa][Ll]' $TCROOT/etc/adjtime 2>/dev/null 1>&2 || LOCALTIME=0
		[ "x$LOCALTIME" = "x0" ] && echo " RTC in local TZ: no" || 
		echo " RTC in local TZ: yes"
		[ "x$LOCALTIME" = "x0" ] || (
			echo ""
			echo "[1;39mWarning: The system is configured to read the RTC time in the local time zone. This" 
			echo "         mode can not be fully supported. It will create various problems with time" 
			echo "         zone changes and daylight saving time adjustments. The RTC time is never updated," 
			echo "         it relies on external facilities to maintain it. If at all possible, use" 
			echo "         RTC in UTC by calling 'timedatectl set-local-rtc 0'[0m." 
		)

	return
	else
		case $1 in 
			set-timezone)
				ln -sf ../usr/share/zoneinfo/$2 $TCROOT/etc/localtime
				;;
			set-local-rtc)
				if bool $2
				then
					echo "0.0 0 0
0
LOCAL" > $TCROOT/etc/adjtime
				else
					rm $TCROOT/etc/adjtime
				fi
				;;
			*)
				echo "Unknown operation $1"
				return 1
				;;
		esac
	fi
}
shift
case $TCCOMMAND in
	hostnamectl)
		tc_hostnamectl $*
		;;
	localectl)
		tc_localectl $*
		;;
	timedatectl)
		tc_timedatectl $*
		;;
	*)
		echo "Supported simulation: hostnamectl localectl timedatectl"
		exit 1
		;;
esac
